name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run_job:
        type: boolean
        required: false
        description: Run Specific Job

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"
  
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Custom Message
        run: echo "Executing KodeKloud Lab 2"